//
// Created by alex on 14.08.26.
//

#ifndef INTRINSICENGINE_GRAPHICS_RENDERER_DEFERRED_CPPM_H
#define INTRINSICENGINE_GRAPHICS_RENDERER_DEFERRED_CPPM_H

#endif //INTRINSICENGINE_GRAPHICS_RENDERER_DEFERRED_CPPM_H
