#!/usr/bin/env python3
"""Generate tasks/SESSION-BRIEF.md from task front-matter.

The brief is the machine-derived session-start view of the task tree: the
currently active tasks plus, per convergence theme, which open backlog tasks
are unblocked (every `depends_on` entry retired to ``tasks/done/``) and which
are blocked (with the first unmet dependency). It is committed and freshness-
checked in CI (``ci-docs.yml``), so bare file-reading clients get the same
view as tool-running agents.

Output is deterministic: no timestamps, stable ordering (theme key, then task
ID), regenerated only when the task tree changes.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from check_audit_cadence import cadence_status  # noqa: E402
from validate_tasks import find_markdown_files, parse_task  # noqa: E402

TITLE_RE = re.compile(r"^#\s+[A-Z]+-\d+[A-Z0-9-]*\s+—\s+(.+)$")

THEME_NAMES = {
    "A": "Shortest path to sandbox visible geometry",
    "B": "Rendering modernization",
    "C": "Physics readiness",
    "D": "ECS hardening parity",
    "E": "Geometry IO completion",
    "F": "Architecture/runtime/UI foundation seeds",
    "G": "Active bugs",
    "H": "Agentic workflow hardening",
    "I": "Research method implementation",
    "none": "Unthemed",
}

OUTPUT_REL = Path("tasks/SESSION-BRIEF.md")


def task_title(parsed) -> str:
    for line in parsed.content.splitlines():
        m = TITLE_RE.match(line.strip())
        if m:
            return m.group(1).strip()
    return "(untitled)"


def load_front_matter(parsed) -> dict | None:
    if parsed.front_matter is None:
        return None
    import yaml

    data = yaml.safe_load(parsed.front_matter)
    return data if isinstance(data, dict) else None


def generate(repo_root: Path) -> str:
    tasks_root = repo_root / "tasks"
    parsed_tasks = [parse_task(p) for p in find_markdown_files(tasks_root)]

    done_ids = {
        t.task_id
        for t in parsed_tasks
        if t.task_id and "done" in {part.lower() for part in t.path.parts}
    }

    active: list[tuple[str, str, Path]] = []
    by_theme: dict[str, list[tuple[str, str, Path, list[str]]]] = {}
    for t in parsed_tasks:
        parts = {part.lower() for part in t.path.parts}
        if "done" in parts or t.task_id is None:
            continue
        meta = load_front_matter(t) or {}
        rel = t.path.relative_to(repo_root)
        if "active" in parts:
            active.append((t.task_id, task_title(t), rel))
            continue
        theme = str(meta.get("theme", "none"))
        deps = [d for d in meta.get("depends_on", []) if isinstance(d, str)]
        by_theme.setdefault(theme, []).append((t.task_id, task_title(t), rel, deps))

    lines: list[str] = []
    lines.append("# Session Brief")
    lines.append("")
    lines.append("Generated by `python3 tools/agents/generate_session_brief.py` from task")
    lines.append("front-matter. Do not edit by hand; regenerate after opening, retiring, or")
    lines.append("re-gating any task. `ci-docs.yml` fails when this file is stale. Theme")
    lines.append("priorities and rationale live in `tasks/backlog/README.md`; this brief is")
    lines.append("the authoritative open/unblocked view.")
    lines.append("")
    lines.append("## Active tasks")
    lines.append("")
    if active:
        for task_id, title, rel in sorted(active):
            lines.append(f"- `{task_id}` — {title} ({rel})")
    else:
        lines.append("- none")

    theme_order = sorted(by_theme, key=lambda k: (k == "none", k))
    for theme in theme_order:
        lines.append("")
        lines.append(f"## Theme {theme} — {THEME_NAMES.get(theme, 'Unknown theme')}"
                     if theme != "none" else "## Unthemed")
        lines.append("")
        for task_id, title, rel, deps in sorted(by_theme[theme]):
            unmet = [d for d in deps if d not in done_ids]
            if unmet:
                lines.append(f"- blocked by `{unmet[0]}`: `{task_id}` — {title} ({rel})")
            else:
                lines.append(f"- unblocked: `{task_id}` — {title} ({rel})")

    lines.append("")
    lines.append("## Audits")
    lines.append("")
    lines.append("Last recorded report per recurring human audit (dates are tree facts so")
    lines.append("this file stays deterministic; overdue judgment comes from")
    lines.append("`python3 tools/agents/check_audit_cadence.py`, also run nightly).")
    lines.append("")
    for name, date, path in cadence_status(repo_root / "docs" / "reports"):
        if date is None:
            lines.append(f"- {name}: no report yet")
        else:
            rel = path.relative_to(repo_root)
            lines.append(f"- {name}: last report {date} ({rel})")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate tasks/SESSION-BRIEF.md.")
    parser.add_argument("--root", default=None, help="Repository root path.")
    parser.add_argument(
        "--check", action="store_true", help="Fail if the committed brief is stale."
    )
    args = parser.parse_args()

    repo_root = Path(args.root).resolve() if args.root else Path(__file__).resolve().parents[2]
    expected = generate(repo_root)
    out_path = repo_root / OUTPUT_REL

    if args.check:
        actual = out_path.read_text(encoding="utf-8") if out_path.is_file() else None
        if actual != expected:
            print(
                f"ERROR: {OUTPUT_REL} is stale. "
                "Run: python3 tools/agents/generate_session_brief.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_REL} is up to date.")
        return 0

    out_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT_REL} ({len(expected.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
